version: '3'
services:
  crdb:
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure
    environment:
      COCKROACH_DATABASE: directory
    ports:
      - 26257:26257
      - 8081:8080
    volumes:
      - ./.dc-data/crdb:/cockroach/cockroach-data

  init-audit:
    image: ghcr.io/metal-toolbox/audittail:v0.5.2
    command: init -f /app-audit/audit.log
    volumes:
      - ./.audit:/app-audit

  audit:
    image: ghcr.io/metal-toolbox/audittail:v0.5.2
    command: -f /app-audit/audit.log
    depends_on:
      - init-audit
    volumes:
      - ./.audit:/app-audit
    restart: unless-stopped

  nats:
    image: nats:2-alpine
    command:
      - ash
      - -ec
      - |
        # add single user with nkey
        cat <<EOF >> /etc/nats/nats-server.conf
        authorization {
          users: [{ nkey: $$(cat /nkey.pub) }]
        }
        EOF

        # start nats server
        nats-server -c /etc/nats/nats-server.conf
    ports:
      - 4222:4222
    volumes:
      - ./nkey.pub:/nkey.pub
