version: '3'

services:
  crdb:
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure
    environment:
      COCKROACH_DATABASE: directory
    ports:
      - 26257:26257
      - 8081:8080
    volumes:
      - ./.dc-data/crdb:/cockroach/cockroach-data

  init-audit:
    image: ghcr.io/metal-toolbox/audittail:v0.6.1
    command: init -f /app-audit/audit.log
    volumes:
      - ./.dc-data/audit:/app-audit

  audit:
    image: ghcr.io/metal-toolbox/audittail:v0.6.1
    command: -f /app-audit/audit.log
    depends_on:
      - init-audit
    volumes:
      - ./.dc-data/audit:/app-audit
    restart: unless-stopped

  nats:
    image: nats:2-alpine
    command:
      - ash
      - -ec
      - |
        # add single user with nkey
        cat <<EOF > /etc/nats/nats-server.conf
        server_name: local-dev

        # Client port of 4222 on all interfaces
        port: 4222

        # HTTP monitoring port
        monitor_port: 8222

        jetstream: true
        jetstream {
          store_dir: /data/jetstream
          max_mem: 10M
          max_file: 1G
        }

        authorization: {
          users: [{ nkey: $$(cat /nkey.pub) }]
        }
        EOF

        # start nats server
        nats-server -c /etc/nats/nats-server.conf
    ports:
      - 4222:4222
    volumes:
      - ./.dc-data/nkey.pub:/nkey.pub

  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:0.5.8
    environment:
      LOG_LEVEL: 'debug'
      SERVER_PORT: '8082'
      JSON_CONFIG_PATH: /app/config.json
    ports:
      - 8082:8082
    volumes:
      - ./.dc-data/oauth2.json:/app/config.json
