// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package v1

import (
	"time"
)

// CreateDirectoryRequest defines model for CreateDirectoryRequest.
type CreateDirectoryRequest struct {
	Metadata *DirectoryMetadata `json:"metadata,omitempty"`
	Name     string             `binding:"required" json:"name"`
	Version  string             `json:"version"`
}

// Directory defines model for Directory.
type Directory struct {
	CreatedAt time.Time          `json:"createdAt"`
	DeletedAt *time.Time         `json:"deletedAt,omitempty"`
	Id        DirectoryID        `json:"id"`
	Metadata  *DirectoryMetadata `json:"metadata,omitempty"`
	Name      string             `binding:"required" json:"name"`
	Parent    *DirectoryID       `json:"parent,omitempty"`
	UpdatedAt time.Time          `json:"updatedAt"`
}

// DirectoryFetch defines model for DirectoryFetch.
type DirectoryFetch struct {
	Directory Directory `json:"directory"`
	Version   string    `json:"version"`
}

// DirectoryList defines model for DirectoryList.
type DirectoryList struct {
	Links       PaginationLinks `json:"_links"`
	Directories []DirectoryID   `json:"directories"`
	Page        int             `json:"page"`
	PageSize    int             `json:"page_size"`
	Version     string          `json:"version"`
}

// DirectoryRequestMeta defines model for DirectoryRequestMeta.
type DirectoryRequestMeta struct {
	Version string `json:"version"`
}

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Link defines model for Link.
type Link struct {
	HREF string `json:"href"`
}

// NewDirectory defines model for NewDirectory.
type NewDirectory struct {
	Metadata *DirectoryMetadata `json:"metadata,omitempty"`
	Name     string             `binding:"required" json:"name"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Links    PaginationLinks `json:"_links"`
	Page     int             `json:"page"`
	PageSize int             `json:"page_size"`
}

// PaginationLinks defines model for PaginationLinks.
type PaginationLinks struct {
	Next *Link `json:"next"`
}

// UpdateDirectoryRequest defines model for UpdateDirectoryRequest.
type UpdateDirectoryRequest struct {
	Metadata *DirectoryMetadata `json:"metadata,omitempty"`
	Name     *string            `json:"name,omitempty"`
	Version  string             `json:"version"`
}

// Limit defines model for limit.
type Limit = int

// Page defines model for page.
type Page = int

// WithDeleted defines model for with_deleted.
type WithDeleted = bool

// GetDirectoryParams defines parameters for GetDirectory.
type GetDirectoryParams struct {
	WithDeleted *WithDeleted `form:"with_deleted,omitempty" json:"with_deleted,omitempty"`
	Page        *Page        `form:"page,omitempty" json:"page,omitempty"`
	Limit       *Limit       `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListChildrenParams defines parameters for ListChildren.
type ListChildrenParams struct {
	WithDeleted *WithDeleted `form:"with_deleted,omitempty" json:"with_deleted,omitempty"`
	Page        *Page        `form:"page,omitempty" json:"page,omitempty"`
	Limit       *Limit       `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListParentsParams defines parameters for ListParents.
type ListParentsParams struct {
	WithDeleted *WithDeleted `form:"with_deleted,omitempty" json:"with_deleted,omitempty"`
	Page        *Page        `form:"page,omitempty" json:"page,omitempty"`
	Limit       *Limit       `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListParentsUntilParams defines parameters for ListParentsUntil.
type ListParentsUntilParams struct {
	WithDeleted *WithDeleted `form:"with_deleted,omitempty" json:"with_deleted,omitempty"`
	Page        *Page        `form:"page,omitempty" json:"page,omitempty"`
	Limit       *Limit       `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListRootsParams defines parameters for ListRoots.
type ListRootsParams struct {
	WithDeleted *WithDeleted `form:"with_deleted,omitempty" json:"with_deleted,omitempty"`
	Page        *Page        `form:"page,omitempty" json:"page,omitempty"`
	Limit       *Limit       `form:"limit,omitempty" json:"limit,omitempty"`
}

// UpdateDirectoryJSONRequestBody defines body for UpdateDirectory for application/json ContentType.
type UpdateDirectoryJSONRequestBody = UpdateDirectoryRequest

// CreateDirectoryJSONRequestBody defines body for CreateDirectory for application/json ContentType.
type CreateDirectoryJSONRequestBody = CreateDirectoryRequest

// CreateRootDirectoryJSONRequestBody defines body for CreateRootDirectory for application/json ContentType.
type CreateRootDirectoryJSONRequestBody = CreateDirectoryRequest
