apiVersion: v2
appVersion: 0.0.1
description: A Helm chart to deploy fertilesoil
name: fertilesoil
version: 0.0.1

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.2.4
