// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/JAORMX/fertilesoil/ent/directory"
	"github.com/JAORMX/fertilesoil/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	directoryHooks := schema.Directory{}.Hooks()
	directory.Hooks[0] = directoryHooks[0]
	directory.Hooks[1] = directoryHooks[1]
	directory.Hooks[2] = directoryHooks[2]
	directory.Hooks[3] = directoryHooks[3]
	directoryFields := schema.Directory{}.Fields()
	_ = directoryFields
	// directoryDescName is the schema descriptor for name field.
	directoryDescName := directoryFields[0].Descriptor()
	// directory.NameValidator is a validator for the "name" field. It is called by the builders before save.
	directory.NameValidator = directoryDescName.Validators[0].(func(string) error)
	// directoryDescCreatedAt is the schema descriptor for created_at field.
	directoryDescCreatedAt := directoryFields[2].Descriptor()
	// directory.DefaultCreatedAt holds the default value on creation for the created_at field.
	directory.DefaultCreatedAt = directoryDescCreatedAt.Default.(func() time.Time)
	// directoryDescUpdatedAt is the schema descriptor for updated_at field.
	directoryDescUpdatedAt := directoryFields[3].Descriptor()
	// directory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	directory.DefaultUpdatedAt = directoryDescUpdatedAt.Default.(func() time.Time)
	// directory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	directory.UpdateDefaultUpdatedAt = directoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// directoryDescIsRoot is the schema descriptor for is_root field.
	directoryDescIsRoot := directoryFields[5].Descriptor()
	// directory.DefaultIsRoot holds the default value on creation for the is_root field.
	directory.DefaultIsRoot = directoryDescIsRoot.Default.(bool)
}

const (
	Version = "v0.11.5-0.20221031135557-521f9b57bc3d"           // Version of ent codegen.
	Sum     = "h1:slfuvOSWSiV0ldHU+V+O2cfOEgWRpbRloUeE9k7wXnw=" // Sum of ent codegen.
)
