// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"github.com/JAORMX/fertilesoil/ent/migrate"

	"github.com/JAORMX/fertilesoil/ent/directory"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Directory is the client for interacting with the Directory builders.
	Directory *DirectoryClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Directory = NewDirectoryClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		Directory: NewDirectoryClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		Directory: NewDirectoryClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Directory.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Directory.Use(hooks...)
}

// DirectoryClient is a client for the Directory schema.
type DirectoryClient struct {
	config
}

// NewDirectoryClient returns a client for the Directory from the given config.
func NewDirectoryClient(c config) *DirectoryClient {
	return &DirectoryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `directory.Hooks(f(g(h())))`.
func (c *DirectoryClient) Use(hooks ...Hook) {
	c.hooks.Directory = append(c.hooks.Directory, hooks...)
}

// Create returns a builder for creating a Directory entity.
func (c *DirectoryClient) Create() *DirectoryCreate {
	mutation := newDirectoryMutation(c.config, OpCreate)
	return &DirectoryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Directory entities.
func (c *DirectoryClient) CreateBulk(builders ...*DirectoryCreate) *DirectoryCreateBulk {
	return &DirectoryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Directory.
func (c *DirectoryClient) Update() *DirectoryUpdate {
	mutation := newDirectoryMutation(c.config, OpUpdate)
	return &DirectoryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DirectoryClient) UpdateOne(d *Directory) *DirectoryUpdateOne {
	mutation := newDirectoryMutation(c.config, OpUpdateOne, withDirectory(d))
	return &DirectoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DirectoryClient) UpdateOneID(id int) *DirectoryUpdateOne {
	mutation := newDirectoryMutation(c.config, OpUpdateOne, withDirectoryID(id))
	return &DirectoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Directory.
func (c *DirectoryClient) Delete() *DirectoryDelete {
	mutation := newDirectoryMutation(c.config, OpDelete)
	return &DirectoryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DirectoryClient) DeleteOne(d *Directory) *DirectoryDeleteOne {
	return c.DeleteOneID(d.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DirectoryClient) DeleteOneID(id int) *DirectoryDeleteOne {
	builder := c.Delete().Where(directory.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DirectoryDeleteOne{builder}
}

// Query returns a query builder for Directory.
func (c *DirectoryClient) Query() *DirectoryQuery {
	return &DirectoryQuery{
		config: c.config,
	}
}

// Get returns a Directory entity by its id.
func (c *DirectoryClient) Get(ctx context.Context, id int) (*Directory, error) {
	return c.Query().Where(directory.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DirectoryClient) GetX(ctx context.Context, id int) *Directory {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryChildren queries the children edge of a Directory.
func (c *DirectoryClient) QueryChildren(d *Directory) *DirectoryQuery {
	query := &DirectoryQuery{config: c.config}
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := d.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(directory.Table, directory.FieldID, id),
			sqlgraph.To(directory.Table, directory.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, directory.ChildrenTable, directory.ChildrenColumn),
		)
		fromV = sqlgraph.Neighbors(d.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryParent queries the parent edge of a Directory.
func (c *DirectoryClient) QueryParent(d *Directory) *DirectoryQuery {
	query := &DirectoryQuery{config: c.config}
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := d.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(directory.Table, directory.FieldID, id),
			sqlgraph.To(directory.Table, directory.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, directory.ParentTable, directory.ParentColumn),
		)
		fromV = sqlgraph.Neighbors(d.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DirectoryClient) Hooks() []Hook {
	hooks := c.hooks.Directory
	return append(hooks[:len(hooks):len(hooks)], directory.Hooks[:]...)
}
