// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/JAORMX/fertilesoil/ent/directory"
	"github.com/JAORMX/fertilesoil/ent/predicate"
)

// DirectoryUpdate is the builder for updating Directory entities.
type DirectoryUpdate struct {
	config
	hooks    []Hook
	mutation *DirectoryMutation
}

// Where appends a list predicates to the DirectoryUpdate builder.
func (du *DirectoryUpdate) Where(ps ...predicate.Directory) *DirectoryUpdate {
	du.mutation.Where(ps...)
	return du
}

// SetName sets the "name" field.
func (du *DirectoryUpdate) SetName(s string) *DirectoryUpdate {
	du.mutation.SetName(s)
	return du
}

// SetMetadata sets the "metadata" field.
func (du *DirectoryUpdate) SetMetadata(s string) *DirectoryUpdate {
	du.mutation.SetMetadata(s)
	return du
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (du *DirectoryUpdate) SetNillableMetadata(s *string) *DirectoryUpdate {
	if s != nil {
		du.SetMetadata(*s)
	}
	return du
}

// ClearMetadata clears the value of the "metadata" field.
func (du *DirectoryUpdate) ClearMetadata() *DirectoryUpdate {
	du.mutation.ClearMetadata()
	return du
}

// SetUpdatedAt sets the "updated_at" field.
func (du *DirectoryUpdate) SetUpdatedAt(t time.Time) *DirectoryUpdate {
	du.mutation.SetUpdatedAt(t)
	return du
}

// SetDeletedAt sets the "deleted_at" field.
func (du *DirectoryUpdate) SetDeletedAt(t time.Time) *DirectoryUpdate {
	du.mutation.SetDeletedAt(t)
	return du
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (du *DirectoryUpdate) SetNillableDeletedAt(t *time.Time) *DirectoryUpdate {
	if t != nil {
		du.SetDeletedAt(*t)
	}
	return du
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (du *DirectoryUpdate) ClearDeletedAt() *DirectoryUpdate {
	du.mutation.ClearDeletedAt()
	return du
}

// AddChildIDs adds the "children" edge to the Directory entity by IDs.
func (du *DirectoryUpdate) AddChildIDs(ids ...int) *DirectoryUpdate {
	du.mutation.AddChildIDs(ids...)
	return du
}

// AddChildren adds the "children" edges to the Directory entity.
func (du *DirectoryUpdate) AddChildren(d ...*Directory) *DirectoryUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return du.AddChildIDs(ids...)
}

// SetParentID sets the "parent" edge to the Directory entity by ID.
func (du *DirectoryUpdate) SetParentID(id int) *DirectoryUpdate {
	du.mutation.SetParentID(id)
	return du
}

// SetNillableParentID sets the "parent" edge to the Directory entity by ID if the given value is not nil.
func (du *DirectoryUpdate) SetNillableParentID(id *int) *DirectoryUpdate {
	if id != nil {
		du = du.SetParentID(*id)
	}
	return du
}

// SetParent sets the "parent" edge to the Directory entity.
func (du *DirectoryUpdate) SetParent(d *Directory) *DirectoryUpdate {
	return du.SetParentID(d.ID)
}

// Mutation returns the DirectoryMutation object of the builder.
func (du *DirectoryUpdate) Mutation() *DirectoryMutation {
	return du.mutation
}

// ClearChildren clears all "children" edges to the Directory entity.
func (du *DirectoryUpdate) ClearChildren() *DirectoryUpdate {
	du.mutation.ClearChildren()
	return du
}

// RemoveChildIDs removes the "children" edge to Directory entities by IDs.
func (du *DirectoryUpdate) RemoveChildIDs(ids ...int) *DirectoryUpdate {
	du.mutation.RemoveChildIDs(ids...)
	return du
}

// RemoveChildren removes "children" edges to Directory entities.
func (du *DirectoryUpdate) RemoveChildren(d ...*Directory) *DirectoryUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return du.RemoveChildIDs(ids...)
}

// ClearParent clears the "parent" edge to the Directory entity.
func (du *DirectoryUpdate) ClearParent() *DirectoryUpdate {
	du.mutation.ClearParent()
	return du
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (du *DirectoryUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if err := du.defaults(); err != nil {
		return 0, err
	}
	if len(du.hooks) == 0 {
		if err = du.check(); err != nil {
			return 0, err
		}
		affected, err = du.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DirectoryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = du.check(); err != nil {
				return 0, err
			}
			du.mutation = mutation
			affected, err = du.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(du.hooks) - 1; i >= 0; i-- {
			if du.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = du.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, du.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (du *DirectoryUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DirectoryUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DirectoryUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (du *DirectoryUpdate) defaults() error {
	if _, ok := du.mutation.UpdatedAt(); !ok {
		if directory.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized directory.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := directory.UpdateDefaultUpdatedAt()
		du.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (du *DirectoryUpdate) check() error {
	if v, ok := du.mutation.Name(); ok {
		if err := directory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Directory.name": %w`, err)}
		}
	}
	return nil
}

func (du *DirectoryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   directory.Table,
			Columns: directory.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: directory.FieldID,
			},
		},
	}
	if ps := du.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.Name(); ok {
		_spec.SetField(directory.FieldName, field.TypeString, value)
	}
	if value, ok := du.mutation.Metadata(); ok {
		_spec.SetField(directory.FieldMetadata, field.TypeString, value)
	}
	if du.mutation.MetadataCleared() {
		_spec.ClearField(directory.FieldMetadata, field.TypeString)
	}
	if value, ok := du.mutation.UpdatedAt(); ok {
		_spec.SetField(directory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := du.mutation.DeletedAt(); ok {
		_spec.SetField(directory.FieldDeletedAt, field.TypeTime, value)
	}
	if du.mutation.DeletedAtCleared() {
		_spec.ClearField(directory.FieldDeletedAt, field.TypeTime)
	}
	if du.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   directory.ChildrenTable,
			Columns: []string{directory.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: directory.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !du.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   directory.ChildrenTable,
			Columns: []string{directory.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: directory.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   directory.ChildrenTable,
			Columns: []string{directory.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: directory.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if du.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   directory.ParentTable,
			Columns: []string{directory.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: directory.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   directory.ParentTable,
			Columns: []string{directory.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: directory.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{directory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// DirectoryUpdateOne is the builder for updating a single Directory entity.
type DirectoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DirectoryMutation
}

// SetName sets the "name" field.
func (duo *DirectoryUpdateOne) SetName(s string) *DirectoryUpdateOne {
	duo.mutation.SetName(s)
	return duo
}

// SetMetadata sets the "metadata" field.
func (duo *DirectoryUpdateOne) SetMetadata(s string) *DirectoryUpdateOne {
	duo.mutation.SetMetadata(s)
	return duo
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (duo *DirectoryUpdateOne) SetNillableMetadata(s *string) *DirectoryUpdateOne {
	if s != nil {
		duo.SetMetadata(*s)
	}
	return duo
}

// ClearMetadata clears the value of the "metadata" field.
func (duo *DirectoryUpdateOne) ClearMetadata() *DirectoryUpdateOne {
	duo.mutation.ClearMetadata()
	return duo
}

// SetUpdatedAt sets the "updated_at" field.
func (duo *DirectoryUpdateOne) SetUpdatedAt(t time.Time) *DirectoryUpdateOne {
	duo.mutation.SetUpdatedAt(t)
	return duo
}

// SetDeletedAt sets the "deleted_at" field.
func (duo *DirectoryUpdateOne) SetDeletedAt(t time.Time) *DirectoryUpdateOne {
	duo.mutation.SetDeletedAt(t)
	return duo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (duo *DirectoryUpdateOne) SetNillableDeletedAt(t *time.Time) *DirectoryUpdateOne {
	if t != nil {
		duo.SetDeletedAt(*t)
	}
	return duo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (duo *DirectoryUpdateOne) ClearDeletedAt() *DirectoryUpdateOne {
	duo.mutation.ClearDeletedAt()
	return duo
}

// AddChildIDs adds the "children" edge to the Directory entity by IDs.
func (duo *DirectoryUpdateOne) AddChildIDs(ids ...int) *DirectoryUpdateOne {
	duo.mutation.AddChildIDs(ids...)
	return duo
}

// AddChildren adds the "children" edges to the Directory entity.
func (duo *DirectoryUpdateOne) AddChildren(d ...*Directory) *DirectoryUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return duo.AddChildIDs(ids...)
}

// SetParentID sets the "parent" edge to the Directory entity by ID.
func (duo *DirectoryUpdateOne) SetParentID(id int) *DirectoryUpdateOne {
	duo.mutation.SetParentID(id)
	return duo
}

// SetNillableParentID sets the "parent" edge to the Directory entity by ID if the given value is not nil.
func (duo *DirectoryUpdateOne) SetNillableParentID(id *int) *DirectoryUpdateOne {
	if id != nil {
		duo = duo.SetParentID(*id)
	}
	return duo
}

// SetParent sets the "parent" edge to the Directory entity.
func (duo *DirectoryUpdateOne) SetParent(d *Directory) *DirectoryUpdateOne {
	return duo.SetParentID(d.ID)
}

// Mutation returns the DirectoryMutation object of the builder.
func (duo *DirectoryUpdateOne) Mutation() *DirectoryMutation {
	return duo.mutation
}

// ClearChildren clears all "children" edges to the Directory entity.
func (duo *DirectoryUpdateOne) ClearChildren() *DirectoryUpdateOne {
	duo.mutation.ClearChildren()
	return duo
}

// RemoveChildIDs removes the "children" edge to Directory entities by IDs.
func (duo *DirectoryUpdateOne) RemoveChildIDs(ids ...int) *DirectoryUpdateOne {
	duo.mutation.RemoveChildIDs(ids...)
	return duo
}

// RemoveChildren removes "children" edges to Directory entities.
func (duo *DirectoryUpdateOne) RemoveChildren(d ...*Directory) *DirectoryUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return duo.RemoveChildIDs(ids...)
}

// ClearParent clears the "parent" edge to the Directory entity.
func (duo *DirectoryUpdateOne) ClearParent() *DirectoryUpdateOne {
	duo.mutation.ClearParent()
	return duo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (duo *DirectoryUpdateOne) Select(field string, fields ...string) *DirectoryUpdateOne {
	duo.fields = append([]string{field}, fields...)
	return duo
}

// Save executes the query and returns the updated Directory entity.
func (duo *DirectoryUpdateOne) Save(ctx context.Context) (*Directory, error) {
	var (
		err  error
		node *Directory
	)
	if err := duo.defaults(); err != nil {
		return nil, err
	}
	if len(duo.hooks) == 0 {
		if err = duo.check(); err != nil {
			return nil, err
		}
		node, err = duo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DirectoryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = duo.check(); err != nil {
				return nil, err
			}
			duo.mutation = mutation
			node, err = duo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(duo.hooks) - 1; i >= 0; i-- {
			if duo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = duo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, duo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Directory)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from DirectoryMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DirectoryUpdateOne) SaveX(ctx context.Context) *Directory {
	node, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (duo *DirectoryUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DirectoryUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (duo *DirectoryUpdateOne) defaults() error {
	if _, ok := duo.mutation.UpdatedAt(); !ok {
		if directory.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized directory.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := directory.UpdateDefaultUpdatedAt()
		duo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (duo *DirectoryUpdateOne) check() error {
	if v, ok := duo.mutation.Name(); ok {
		if err := directory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Directory.name": %w`, err)}
		}
	}
	return nil
}

func (duo *DirectoryUpdateOne) sqlSave(ctx context.Context) (_node *Directory, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   directory.Table,
			Columns: directory.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: directory.FieldID,
			},
		},
	}
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Directory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := duo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, directory.FieldID)
		for _, f := range fields {
			if !directory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != directory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := duo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := duo.mutation.Name(); ok {
		_spec.SetField(directory.FieldName, field.TypeString, value)
	}
	if value, ok := duo.mutation.Metadata(); ok {
		_spec.SetField(directory.FieldMetadata, field.TypeString, value)
	}
	if duo.mutation.MetadataCleared() {
		_spec.ClearField(directory.FieldMetadata, field.TypeString)
	}
	if value, ok := duo.mutation.UpdatedAt(); ok {
		_spec.SetField(directory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := duo.mutation.DeletedAt(); ok {
		_spec.SetField(directory.FieldDeletedAt, field.TypeTime, value)
	}
	if duo.mutation.DeletedAtCleared() {
		_spec.ClearField(directory.FieldDeletedAt, field.TypeTime)
	}
	if duo.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   directory.ChildrenTable,
			Columns: []string{directory.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: directory.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !duo.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   directory.ChildrenTable,
			Columns: []string{directory.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: directory.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   directory.ChildrenTable,
			Columns: []string{directory.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: directory.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if duo.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   directory.ParentTable,
			Columns: []string{directory.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: directory.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   directory.ParentTable,
			Columns: []string{directory.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: directory.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Directory{config: duo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{directory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
