apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    # TODO: Does fertilsoil need audit enabled always?
    {{- if .Values.audit.enabled }}
      initContainers:
      # Optional: Pre-creates the `/app-audit/audit.log` named pipe.
      - image: "{{ .Values.audit.image.registry }}/{{ .Values.audit.image.repository }}:{{ .Values.audit.image.tag | default .Chart.AppVersion }}"
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        args:
          - 'init'
          - '-f'
          - '/app-audit/audit.log'
        name: init-audit-logs
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /app-audit
            name: audit-logs
      {{- with .Values.audit.init.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
      {{- end }}
    {{- end }}
      containers:
        - name: {{ template "common.names.fullname" . }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- with .Values.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          env:
            {{- with .Values.fertilesoil.database.host }}
            - name: FERTILESOIL_CRDB_HOST
              value: "{{ . }}"
            {{- end }}
            {{- with .Values.fertilesoil.database.params }}
            - name: FERTILESOIL_CRDB_PARAMS
              value: "{{ . }}"
            {{- end }}
            {{- with .Values.fertilesoil.database.user }}
            - name: FERTILESOIL_CRDB_USER
              value: "{{ . }}"
            {{- end }}
            {{- if .Values.fertilesoil.database.readOnly }}
            - name: FERTILESOIL_CRDB_READ_ONLY
              value: "true"
            {{- end }}
            {{- if .Values.fertilesoil.database.fastReads }}
            - name: FERTILESOIL_CRDB_FAST_READS
              value: "true"
            {{- end }}
            {{- if .Values.fertilesoil.oidc.enabled }}
            {{- with .Values.fertilesoil.oidc.audience }}
            - name: FERTILESOIL_OIDC_AUDIENCE
              value: "{{ . }}"
            {{- end }}
            {{- with .Values.fertilesoil.oidc.issuer }}
            - name: FERTILESOIL_OIDC_ISSUER
              value: "{{ . }}"
            {{- end }}
            {{- with .Values.fertilesoil.oidc.jwks.uri }}
            - name: FERTILESOIL_OIDC_JWKSURI
              value: "{{ . }}"
            {{- end }}
            {{- with .Values.fertilesoil.oidc.jwks.remoteTimeout }}
            - name: FERTILESOIL_OIDC_JWKSREMOTETIMEOUT
              value: "{{ . }}"
            {{- end }}
            {{- else }}
            - name: FERTILESOIL_OIDC_ENABLED
              value: "false"
            {{- end }}
            {{- if .Values.fertilesoil.logging.debug }}
            - name: FERTILESOIL_LOGGING_DEBUG
              value: "true"
            {{- end }}
            {{- if .Values.fertilesoil.logging.pretty }}
            - name: FERTILESOIL_LOGGING_PRETTY
              value: "true"
            {{- end }}
            {{- with .Values.fertilesoil.shutdownTimeout }}
            - name: FERTILESOIL_SERVER_SHUTDOWN
              value: "{{ . }}"
            {{- end }}
            {{- with .Values.fertilesoil.trustedProxies }}
            - name: FERTILESOIL_SERVER_TRUSTED_PROXIES
              value: "{{ join " " . }}"
            {{- end }}
          {{- if .Values.fertilesoil.database.envSecretName }}
          envFrom:
            {{- with .Values.fertilesoil.database.envSecretName }}
            - secretRef:
                name: "{{ . }}"
            {{- end }}
          {{- end }}
          args:
            - "serve"
            {{- with .Values.fertilesoil.nats }}
            - "--nats-url"
            - "{{ .url }}"
            {{- with .subjectPrefix }}
            - "--nats-subject-prefix"
            - "{{ . }}"
            {{- end }}
            {{- with .stream.name }}
            - "--nats-stream-name"
            - "{{ . }}"
            {{- end }}
            {{- with .stream.storageType }}
            - "--nats-stream-storage"
            - "{{ . }}"
            {{- end }}
            {{- if eq .auth.method "creds" }}
            - "--nats-creds"
            - "/data/nats/auth/creds"
            {{- else if eq .auth.nkey "nkey" }}
            - "--nats-nkey"
            - "/data/nats/auth/nkey"
            {{- end }}
            {{- end }}
            {{- with .Values.audit.enabled }}
            - "--audit-log-path"
            - "/data/audit"
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /livez
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: nats-auth
              mountPath: /data/nats/auth
            {{- if .Values.audit.enabled }}
            - name: audit-logs
              mountPath: /data/audit
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- if .Values.audit.enabled }}
      # This is the audit container
        - name: {{ template "common.names.fullname" . }}-audit
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - -f
            - /app-audit/audit.log
          image: "{{ .Values.audit.image.registry }}/{{ .Values.audit.image.repository }}:{{ .Values.audit.image.tag | default .Chart.AppVersion }}"
          volumeMounts:
            - name: audit-logs
              mountPath: /app-audit
          {{- with .Values.audit.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: nats-auth
          secret:
            secretName: "{{ .Values.fertilesoil.nats.auth.secretName }}"
        {{- if .Values.audit.enabled }}
        - name: audit-logs
          emptyDir: {}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
